[package]
name = "i-should-learn-kernel-dev"
version = "0.1.0"
edition = "2021"

[dependencies]
x86_64 = { version = "0.15.1", default-features = false, features = ['instructions'] }
limine = { version = "0.2.0" }
